### ISSUE TITLE
docker login breaks when docker is chalk binary

### ISSUE THREAD

**Issue by miki725** [crashappsec/chalk#194]
## Description

in github actions when doing:

```
      - name: Set up Chalk
        uses: crashappsec/setup-chalk-action@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
```

it then forever hangs on login step.

this could possible be artifact of chalk executing something else on `chalk login`?

## Impact

order of operations is important as chalk==docker binary is not compatible with vanilla docker binary
